module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/features/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'absolute',
    'border',
    'border-solid',
    'border-transparent',
    'border-blueGray-300',
    'bg-white',
    'duration-200',
    'flex',
    'flex-wrap',
    'focus:ring',
    'focus:ring-1',
    'focus:border-lightBlue-500',
    'focus:ring-lightBlue-500',
    'h-full',
    'items-center',
    'items-stretch',
    'mb-3',
    'outline-none',
    'placeholder-blueGray-200',
    'pl-3',
    'pt-0',
    'pl-10',
    'px-2',
    'px-3',
    'py-2',
    'py-3',
    'text-sm',
    'relative',
    'right-0',
    'rounded-md',
    'shadow',
    'text-center',
    'transition',
    'w-8',
    'w-full',
    'z-10',
    'md:w-1/4',
    'md:w-1/2',
    'text-white',
    'text-blueGray-300',
    'text-blueGray-400',
    'text-blueGray-700',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
  ],
  theme: {
    extend: {
      backgroundColor: {
        'site-overlay': 'hsla(0,0%,7%,.36)',
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: '#ffffff',
        purple: '#3f3cbb',
        midnight: '#121063',
        metal: '#565584',
        tahiti: '#3ab7bf',
        silver: '#evebff',
        'bubble-gum': '#ff77e9',
        bermuda: '#78dcca',
        blueGray: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        lightBlue: {
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        facebook: {
          regular: '#3b5999',
          active: '#344e87',
        },
        twitter: {
          regular: '#1da1f2',
          active: '#0d95e8',
        },
        instagram: {
          regular: '#e4405f',
          active: '#e02549',
        },
        github: {
          regular: '#222',
          active: '#131313',
        },
        pinterest: {
          regular: '#bd081c',
          active: '#a00718',
        },
        youtube: {
          regular: '#cd201f',
          active: '#b21c1b',
        },
        vimeo: {
          regular: '#1ab7ea',
          active: '#13a3d2',
        },
        slack: {
          regular: '#3aaf85',
          active: '#329874',
        },
        dribbble: {
          regular: '#ea4c89',
          active: '#e73177',
        },
        reddit: {
          regular: '#ff4500',
          active: '#e03d00',
        },
        tumblr: {
          regular: '#35465c',
          active: '#2a3749',
        },
        linkedin: {
          regular: '#0077b5',
          active: '#00669c',
        },
      },
      minHeight: {
        'site-content': 'calc(100vh - 298)', // Header 56 | Footer 242
      },
      spacing: {
        'mobile-nav': '320px',
        '2-mobile-nav': '640px',
      },
      backgroundPosition: {
        '50-center': '50% center',
      },
    },
    extends: {
      height: {
        'screen-50': '50vh',
      },
    },
  },
};
